### ISSUE TITLE
已安装的软件包 kernel 版本不兼容，要求 5.4.39-1-31848290… 而 5.4.33-1-32cea31f… 已安装。

### ISSUE THREAD

**Issue by 456vv** [x-wrt/x-wrt#104]
安装软件，提示 kernel 版本低，怎么处理？

**Comment by ptpt52** [comment]
内核模块打包编译才能。不然版本不一样无法安装。

**Comment by 456vv** [comment]
这个 kernel 可以更新一下吗！好多安装包都安装不了。

**Comment by ptpt52** [comment]
要安装啥kernel模块，自己编译多好
无论什么时候发布的x-wrt估计，都不一定和官方最新保持一致的
x-wrt每周都更新版本，kernel也会更新，和openwrt官方最新同步的。

**Comment by 456vv** [comment]
我的kernel版本是5.4.33-1-32cea31f22723dde414d2641b0626d22
我在 https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/kmods/找到的只有5.4.33-1-281aa9919f75dad402abf9c3f53f1145

我尝试替换/etc/opkg/distfeeds.conf 文件中的 src/gz openwrt_core 路径。
由于后面的标识号不一样，所以软件无法继续安装。

**Comment by 456vv** [comment]
暂时使用替换版标识号方法来解决，应该不会有太大问题。

参考：
https://koolshare.cn/thread-166730-1-1.html
https://koolshare.cn/thread-166730-1-1.html
http://www.iytc.net/wordpress/?p=1022
