### ISSUE TITLE
建议增加P&W R619AC支持min pcie的接口

### ISSUE THREAD

**Issue by 456vv** [x-wrt/x-wrt#106]
PandoraBox是支持的，我们这个x-wrt能否也让它支持？ 

参考：
http://www.pangubox.com:6380/lintel/R619AC/README.txt
3.Q:支持SATA扩展卡么?
  A: 支持,请用AHCI标准驱动的卡,比如ASM1061,淘宝有卖,参考FAQ21,补齐PCIE缺少的电阻.

**Comment by ptpt52** [comment]
需要硬件改的，暂不考虑支持。

**Comment by ptpt52** [comment]
close

**Comment by ptpt52** [comment]
close test
