### ISSUE TITLE
Cannot access ssh or login luci

### ISSUE THREAD

**Issue by eminhaqi** [x-wrt/x-wrt#134]
Hello, I updated my router (Xiaomi mi wifi R3) without keep settings option. After the update, I cannot log in luci, which gives me "Invalid username and/or password! Please try again." error. Also when I try to access the router via ssh, I am getting "Permission denied (publickey)" error. Btw I did all steps with lan connection because also I cannot access wifi. I don't know the new password of wifi.

**Comment by ptpt52** [comment]
if `without keep settings`
the default password is `admin`

**Comment by eminhaqi** [comment]
Wow thanks, it worked. I confused bcs openwrt's default password blank and could not find any info in the internet. Thanks again.
