### ISSUE TITLE
每次登录管理界面都会跳转到设置向导

### ISSUE THREAD

**Issue by R-YaTian** [x-wrt/x-wrt#135]
RT，请问这是bug吗
版本是8.0-20201107

**Comment by ptpt52** [comment]
是故意的。

**Comment by R-YaTian** [comment]
> 是故意的。
Microsoft Edge 浏览器 86.0.622.63  管理页面输完密码登录后，有大概率出现这个错误:
SyntaxError
Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
然后卡在 正在载入视图… 刷新页面后正常
不知道是不是浏览器问题，Cent 浏览器 80.0.3987.163 没有出现这个问题

**Comment by ptpt52** [comment]
可能是浏览器缓存导致的问题吧
