### ISSUE TITLE
Xiaomi Mi Router R3 WDS not working

### ISSUE THREAD

**Issue by mohalisad** [x-wrt/x-wrt#138]
**Describe the bug**
When I enable wds for a wireless client after that I cannot ping any ip in that subnet from router
Wds broke the wireless connection;

**Expected behavior**
Wds worked and the connection not broke

**Comment by ptpt52** [comment]
@mohalisad 

Unable to reproduce your problem
wds works normally, did you forget to set the wds AP mode of the opposite end?

**Comment by mohalisad** [comment]
Thanks for your response
The actual problem that I have is the original firmware mi router has a repeater feature and that worked with my current network fantasticly now I need to replicate that feature in x wrt without changing the ap side

how can i do that?

I mean what technology the original fw used to do that

**Comment by ptpt52** [comment]
not really sure how the oem firmware do it
but if you want to get wds client work on openwrt, AP wds should be enable on the other end

**Comment by mohalisad** [comment]
Ok
thanks in advance
