### ISSUE TITLE
系统没有 /boot/vmlinuz* 这个文件怎么安装在VPS上面

### ISSUE THREAD

**Issue by 456vv** [x-wrt/x-wrt#140]
CentOS/Debian/Ubuntu 都试了，/boot/目录下，没有文件。强制使用dd错误，dd: failed to open '/dev/ploop18760': Operation not permitted

**Comment by ptpt52** [comment]
有的，ubunt等系统肯定有。

**Comment by 456vv** [comment]
发问题问题所在，KVM 有 boot/vmlinuz*文件。OpenVZ 没有。 OpenVZ是共享内核。
