### ISSUE TITLE
新增软件失败

### ISSUE THREAD

**Issue by wavelet001** [x-wrt/x-wrt#148]
我在.config中同时新增4个软件：
CONFIG_PACKAGE_luci-app-frpc=y
CONFIG_PACKAGE_luci-app-frps=y
CONFIG_PACKAGE_luci-app-hd-idle=y
CONFIG_PACKAGE_luci-app-smartdns=y
结果编译出来的固件，没有网络，但是如果单独新增其中一个软件却一切正常。

![76266C69-0054-44BE-B929-106A6CDEFEAE](https://user-images.githubusercontent.com/58981899/103126622-d58b9e80-46c9-11eb-94e0-938a6370c8a6.jpeg)

![ED7451F9-F0CF-4363-85B3-8FC52BCAD5A4](https://user-images.githubusercontent.com/58981899/103126585-bbea5700-46c9-11eb-8f59-5a21502aad48.jpeg)

**Comment by wavelet001** [comment]
再次编译了一次，现在只加入：
CONFIG_PACKAGE_luci-app-frpc=y
CONFIG_PACKAGE_luci-app-frps=y
CONFIG_PACKAGE_luci-app-smartdns=y
故障依旧。

**Comment by ptpt52** [comment]
加入这几个，固件大小是否超了？

.config 里面 CONFIG_TARGET_ROOTFS_PARTSIZE= 设置 root 分区大小

**Comment by wavelet001** [comment]
再次编译了一次，这次这样的组合就一切正常了。
CONFIG_PACKAGE_luci-app-frpc=y
CONFIG_PACKAGE_luci-app-hd-idle=y
CONFIG_PACKAGE_luci-app-smartdns=y

**Comment by wavelet001** [comment]
但是登陆页面却出现了SmartDNS的选项。

![微信截图_20201225194519](https://user-images.githubusercontent.com/58981899/103134128-dd5b3b00-46e9-11eb-82f2-fdc1d7b571a4.png)

**Comment by ptpt52** [comment]
有些app 太老了不兼容很正常。官方源才正常。

**Comment by wavelet001** [comment]
请问默认配置用的是不是官方源？

**Comment by ptpt52** [comment]
你浏览器缓存问题吧

**Comment by wavelet001** [comment]
> 你浏览器缓存问题吧

不是，我用的是隐私模式，而且还使用了不同的浏览器。

**Comment by wavelet001** [comment]
> 加入这几个，固件大小是否超了？
> 
> .config 里面 CONFIG_TARGET_ROOTFS_PARTSIZE= 设置 root 分区大小

大神就是大神，将它设置成1024就一切正常了。

**Comment by ptpt52** [comment]
> > 加入这几个，固件大小是否超了？
> > .config 里面 CONFIG_TARGET_ROOTFS_PARTSIZE= 设置 root 分区大小
> 
> 大神就是大神，将它设置成1024就一切正常了。

也不是改越大越好，改刚好合适就行。
boot分区是 CONFIG_TARGET_KERNEL_PARTSIZE=
这两个分区，加起来，如果刚好256最好，如果256不够，就512，……

这两个分区加起来的大小，就是生产固件的大小（解压后）
影响刷机速度，影响刷机时候占用内存大小。

**Comment by wavelet001** [comment]
> > > 加入这几个，固件大小是否超了？
> > > .config 里面 CONFIG_TARGET_ROOTFS_PARTSIZE= 设置 root 分区大小
> > 
> > 
> > 大神就是大神，将它设置成1024就一切正常了。
> 
> 也不是改越大越好，改刚好合适就行。
> boot分区是 CONFIG_TARGET_KERNEL_PARTSIZE=
> 这两个分区，加起来，如果刚好256最好，如果256不够，就512，……
> 
> 这两个分区加起来的大小，就是生产固件的大小（解压后）
> 影响刷机速度，影响刷机时候占用内存大小。

哦！原来是这样，谢谢，谢谢！
