### ISSUE TITLE
请问编译前如何修改IP地址？

### ISSUE THREAD

**Issue by wavelet001** [x-wrt/x-wrt#149]
我将以下源文件中的192.168.15.1都替换成192.168.168.1了，请问为什么编译出来的固件IP还是：192.168.15.1？

![IP](https://user-images.githubusercontent.com/58981899/103144507-5cda2000-4765-11eb-885f-3fded93f69c6.JPG)

**Comment by x-wrt-dev** [comment]
请参考 https://github.com/x-wrt/x-wrt/commit/0d496504dff7d8cb532a3c9c20703ad6344cb98e

**Comment by wavelet001** [comment]
#
