### ISSUE TITLE
MT7621-MT7615E-MT7615E

### ISSUE THREAD

**Issue by guduren9089** [x-wrt/x-wrt#15]
能出一个 MT7621-MT7615E-MT7615E  就好了

**Comment by ptpt52** [comment]
开源驱动不支持，MTK SDK代码可以支持，但是需要折腾一下，待定。

**Comment by ptpt52** [comment]
好消息，有大神正在些7615开源驱动，不久的将来将会支持 https://github.com/LorenzoBianconi/wireless-drivers-next/tree/mt7615-devel

**Comment by laomao9000** [comment]
MT76开源驱动已经支持7615e了
