### ISSUE TITLE
R7000P

### ISSUE THREAD

**Issue by MMBBao** [x-wrt/x-wrt#16]
This repository is a mirror of our main repo at https://git.openwrt.org/openwrt/openwrt.git
It is for reference only and is not active for checkins or for reporting issues.

All issues should be reported at: https://bugs.openwrt.org

Please do not open any NEW issue here - we will be closing the Github issues
capability in the near future.

We will continue to accept Pull Requests here as described in the repo description.

Close this now and click here: https://bugs.openwrt.org

Thankyou for your co-operation.

**Comment by MMBBao** [comment]
能添加支持一下R7000P吗

**Comment by ptpt52** [comment]
博通芯片，放弃治疗吧，不支持的。
