### ISSUE TITLE
[SUGESTION] - Cross check when compiling

### ISSUE THREAD

**Issue by ZacharyFoxx** [x-wrt/x-wrt#162]
Hello.

I was compiling a new version to support minidlna, in addition to nfs support.

Well, I used as a base the file config.ramips-mt7620, following as instructed in issue # 123, adding as a module the minidlna, ffmpeg, rtorrent.

Also, in libraries, I checked to use libffmpeg-custom as a module. For the file system, I decided to leave support for f2fs and exfat embedded in the kernel.

Everything compiled normally but at the end I had the following error in the installation:

```
* check_data_file_clashes: Package kmod-exfat-linux wants to install file /home/zach/Documents/temp/x-wrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/target-dir-7552a1a5/lib/modules/5.10 /exfat.ko
But that file is already provided by package * kmod-fs-exfat
 * opkg_install_cmd: Cannot install package kmod-exfat-linux.
```

I looked for the kmod-exfat-linux package on the wiki and the openwrt packages, but I didn't find anything about it, just about kmod-fs-exfat.

So, looking in the x-wrt github I found what kmod-exfat-linux would be and, if I understand correctly, it is your implementation to already compile x-wrt with exfat support, correct?

If so, as a suggestion, is it possible to include a cross check to avoid this error?

**Comment by ptpt52** [comment]
Please dont select kmod-fs-exfat and use kmod-exfat-linux only
or use kmod-fs-exfat and drop kmod-exfat-linux
