### ISSUE TITLE
luci software page working with downgraded luci-app-opkg from openwrt not with the version which came with xwrt default

### ISSUE THREAD

**Issue by r1riyad** [x-wrt/x-wrt#167]
**Describe the bug**
whenever i install a luci theme there is a option called software where user can manage all the openwrt packages using browser, the link for access https://192.168.* .* /cgi-bin/luci/admin/system/opkg
but the page does not work with xwrt default luci-app-opkg_****.opkg .if i force downgrade this package with the version from here https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/luci/ 
then it works i will add the snapshots below

**To Reproduce**
1. install a luci theme
2. goto '192.168.* .* /cgi-bin/luci/admin/system/opkg'
3. it will show blank page

**Expected behavior**
it was expected to show the opkgs that are installed or can be updated check 2nd ss.

**Screenshots**
1st ss - with default 'luci-app-opkg'
![Screenshot 2021-05-17 15:22:52](https://user-images.githubusercontent.com/33262712/118465524-c7472900-b723-11eb-9f11-1187723ee48b.png)

2nd ss - with 'luci-app-opkg' from https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/luci/ (installed by force downgrade)

![Screenshot 2021-05-17 15:27:34](https://user-images.githubusercontent.com/33262712/118466442-adf2ac80-b724-11eb-9f4a-4512748f1247.png)

**Comment by ptpt52** [comment]
not a bug, I disable it.

**Comment by ptpt52** [comment]
The target users of x-wrt are not people who use opkg luci web, it makes the interface complicated, and unexpected problems occur after installing other software

**Comment by r1riyad** [comment]
Thanks for the clearance. Then i m closing the issue.thank u again
