### ISSUE TITLE
偶然看到这里有dw33d大麦固件，请问下

### ISSUE THREAD

**Issue by bauw2008** [x-wrt/x-wrt#169]
1、因为这个路由2.4g会导致重启，这里的固件是有2.4g和5g的吧.
2、另外能介绍下怎么在编译时，去掉2.4g部份吗。
   感谢大神。

**Comment by ptpt52** [comment]
编译时 `kmod-ath9k=y`改成  kmod-ath9k=m 去掉2.4G

另外2.4G好像没有问题呀。

**Comment by bauw2008** [comment]
这个路由2.4g冷启动会启动不了，应该是硬件虚焊吧，有这问题的不少，不用2.4g就正常。大神，另外问下kmod-ath9k=m这个编译是修改.config这个吧，新手自己尝试弄，还是很清楚。刚看了下CONFIG_DEFAULT_kmod-ath9k=m。另外还有一处是CONFIG_PACKAGE_kmod-ath9k=y不用改吧。。。感谢回复。

**Comment by AmadeusGhost** [comment]
> 另外还有一处是 CONFIG_PACKAGE_kmod-ath9k=y 不用改吧

CONFIG_PACKAGE_kmod-ath9k=y 也要改成 m

**Comment by bauw2008** [comment]
是的，这三个点全改了，已经编译成功。看来还是找个风枪才行，少了2.4G还是有点可惜。
