### ISSUE TITLE
希望增加软件包

### ISSUE THREAD

**Issue by 1248429482** [x-wrt/x-wrt#17]
希望增加软件包，直接在里面选择软件包安装很方便，去掉不习惯用命令

**Comment by daiaji** [comment]
Luci一直可以添加软件包啊

**Comment by cnbohu** [comment]
希望软件包回来。
还有就是能否增加一个 Web页面，可以执行shell命令，比较方便。

**Comment by ptpt52** [comment]
ssh 开启后，登录，执行命令开启 
`rm /etc/adv_luci_disabled`

**Comment by shake** [comment]
我去验证一下，我确实是发现没有我的软件，有装别的。

**Comment by shake** [comment]
来一个教程，如何实现科学的玩法？
