### ISSUE TITLE
Can't install batman adv

### ISSUE THREAD

**Issue by gitnewcomer** [x-wrt/x-wrt#170]
Hi,

I am trying to install batman adv on my Mi Router 3 with command `opkg install kmod-batman-adv` but it always fails because kernel version is not compatible. How can I fix this problem? Are you planning to add support for mesh networks? I already have installed and configured 802.11s mesh (removed `wpad-openssl` and installed `wpad-mesh-openssl`), but because it is based on openwrt, it also have the same problem reported on the openwrt firmware that is still not fixed: https://forum.openwrt.org/t/bug-report-802-11s-mesh-v19-07-4/
There is also a note on the official openwrt configuration page (https://openwrt.org/docs/guide-user/network/wifi/mesh/80211s):

> There appears to be an ARP relay bug (confirmed in v19.07.4) that means meshing only works reliably from the Mesh-Points that are in wireless range of the Mesh Portal (MPP).

This is why I would like to install batman adv for the routing part...

Thanks! :)

**Comment by ptpt52** [comment]
build your firmware from source: https://github.com/x-wrt/x-wrt.github.io/blob/master/docs/build/README.md
