### ISSUE TITLE
wan6端口pppoe拨号成功但获取不到ipv6地址

### ISSUE THREAD

**Issue by cnbohu** [x-wrt/x-wrt#18]
使用wan6端口pppoe拨号成功，但获取不到ipv6地址。
联通，newifi3，应该如何设置
另外网站的ipv6教程也是空的。

**Comment by ptpt52** [comment]
新版本有设置向导，设置向导如果设置了pppoe拨号，会自动帮配置好ipv6

官方文档还在整理，后面才会发出来。

**Comment by ptpt52** [comment]
新版本已经解决。
