### ISSUE TITLE
Mysterious log messages

### ISSUE THREAD

**Issue by xesarni** [x-wrt/x-wrt#184]
> Fri Sep 17 15:34:09 2021 kern.warn kernel: [1009460.430080] warning: do not keep alive: ct no found
Fri Sep 17 15:34:09 2021 kern.warn kernel: [1009460.435146] warning: do not keep alive
Fri Sep 17 15:43:18 2021 kern.warn kernel: [1010010.238327] warning: do not keep alive: ct no found
Fri Sep 17 15:43:18 2021 kern.warn kernel: [1010010.243409] warning: do not keep alive
Fri Sep 17 15:43:34 2021 kern.warn kernel: [1010025.345987] warning: do not keep alive: ct no found
Fri Sep 17 15:43:34 2021 kern.warn kernel: [1010025.351053] warning: do not keep alive

What do they mean?

**Comment by ptpt52** [comment]
log from kmod-natflow
for fast hardware nat.
