### ISSUE TITLE
wireguard on x-wrt ?

### ISSUE THREAD

**Issue by randomername** [x-wrt/x-wrt#193]
i am using  X-WRT 9.0_b202110142350 on a mi 3 router

i am trying to use wireguard but i dont see how to.
there is no place to install a package either.

this is what shows under STATUS > WIREGUARD
![wireguard](https://user-images.githubusercontent.com/93120441/140276844-033cc8a2-527e-4b64-b5f4-20e31dab7dba.JPG)

please point me in the right direction.

**Comment by ptpt52** [comment]
it is ready to use
try Network - interfaces - create new - select protocol

**Comment by randomername** [comment]
than

> it is ready to use try Network - interfaces - create new - select protocol

thank you so much.

i have one more issue.

i have a usb stick plugged into my main router that i want to access using the x-wrt router too.

the x-wrt is running a wireguard VPN and has kill switch firewall rules.

i am unable to even ping the host router from which x-wrt draws the internet
