### ISSUE TITLE
稳定性问题

### ISSUE THREAD

**Issue by hezlog** [x-wrt/x-wrt#20]
问题：
运行一段时间后路由器死机，可以显示WiFi信号，手机、电脑都不能连接，不能获取DHCP IP地址。需要断电重启路由。
运行环境：小米路由3
固件版本：x-wrt-5.0-b201902071033-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.bin

**Comment by ptpt52** [comment]
挂掉后，换网线连接可以正常吗？这样可以定位到是否是无线模块

**Comment by hezlog** [comment]
无线模块似乎没有挂。可以搜索到SSID，可以连接，无法获取到IP，刷了最新版似乎没有出现了。
