### ISSUE TITLE
natflow fails to build

### ISSUE THREAD

**Issue by bbilas** [x-wrt/x-wrt#206]
e83723cfcf version fails to build natflow (natflow-20211210) 

<pre>
/home/bartekk/Projects/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/natflow-20211210/natflow_user.c: In function 'natflow_user_pre_hook':
/home/bartekk/Projects/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/natflow-20211210/natflow_user.c:709:42: error: 'br_in' undeclared (first use in this function)
  709 |         if (!natflow_is_lan_zone(in) && (br_in == NULL || !natflow_is_lan_zone(br_in))) {
      |                                          ^~~~~
/home/bartekk/Projects/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/natflow-20211210/natflow_user.c:709:42: note: each undeclared identifier is reported only once for each function it appears in
/home/bartekk/Projects/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/natflow-20211210/natflow_user.c: In function 'natflow_user_forward_hook':
/home/bartekk/Projects/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/natflow-20211210/natflow_user.c:899:50: error: 'br_in' undeclared (first use in this function)
  899 |                 if (!natflow_is_lan_zone(in) && (br_in == NULL || !natflow_is_lan_zone(br_in))) {
      |                                                  ^~~~~
/home/bartekk/Projects/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/natflow-20211210/natflow_user.c: In function 'natflow_user_post_hook':
/home/bartekk/Projects/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/natflow-20211210/natflow_user.c:1064:50: error: 'br_out' undeclared (first use in this function); did you mean 'xt_out'?
 1064 |                 if (natflow_is_lan_zone(out) || (br_out && natflow_is_lan_zone(br_out))) {
      |                                                  ^~~~~~
      |                                                  xt_out
make[5]: *** [scripts/Makefile.build:262: /home/bartekk/Projects/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/natflow-20211210/natflow_user.o] Error 1
make[4]: *** [Makefile:1734: /home/bartekk/Projects/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/natflow-20211210] Error 2
make[4]: Leaving directory '/home/bartekk/Projects/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.162'
make[3]: *** [Makefile:94: /home/bartekk/Projects/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/natflow-20211210/.built] Error 2
make[3]: Leaving directory '/home/bartekk/Projects/openwrt/x-wrt/feeds/x/natflow'
time: package/feeds/x/natflow/compile#1.65#0.57#2.22
    ERROR: package/feeds/x/natflow failed to build.
make[2]: *** [package/Makefile:116: package/feeds/x/natflow/compile] Error 
</pre>

Target profile: Netgear R6220

**Comment by ptpt52** [comment]
thanks for the report
should be fixed in https://github.com/x-wrt/com.x-wrt/commit/fe2f713d136130a9b21760962c59d04abfc120ac
