### ISSUE TITLE
GCC11编译报错，MT7621

### ISSUE THREAD

**Issue by jxph1123** [x-wrt/x-wrt#224]
d" "LIBCFLAGS=-O2 -I/home/etek/x-wrt/staging_dir/host/include " "NM=nm" "PICFLAG=" "RANLIB=ranlib" "DESTDIR=" DO=all multi-do # make
make[5]: Leaving directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/zlib'
make[5]: Entering directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/libbacktrace'
make  all-am
make[6]: Entering directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/libbacktrace'
true  DO=all multi-do # make
make[6]: Leaving directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/libbacktrace'
make[5]: Leaving directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/libbacktrace'
make[5]: Entering directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/libcpp'
test -f config.h || (rm -f stamp-h1 && make stamp-h1)
make[5]: Leaving directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/libcpp'
make[5]: Entering directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/libcody'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/libcody'
make[5]: Entering directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/libdecnumber'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/libdecnumber'
make[5]: Entering directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/fixincludes'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/fixincludes'
make[5]: Entering directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/gcc'
build/genmatch --gimple /home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/match.pd \
    > tmp-gimple-match.c
GIMPLE decision tree has 3776 leafs, maximum depth 28 and a total number of 16107 nodes
removed 2476 duplicate tails
build/genmatch --generic /home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/match.pd \
    > tmp-generic-match.c
GENERIC decision tree has 3511 leafs, maximum depth 13 and a total number of 14666 nodes
removed 2400 duplicate tails
/bin/bash /home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../move-if-change tmp-gimple-match.c \
    					gimple-match.c
/bin/bash /home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../move-if-change tmp-generic-match.c \
    					generic-match.c
echo timestamp > s-match
g++  -fno-PIE -c   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings  -Wno-unused -DHAVE_CONFIG_H -I. -I. -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/. -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../include -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libcpp/include -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libcody -I/home/etek/x-wrt/staging_dir/host/include -I/home/etek/x-wrt/staging_dir/host/include -I/home/etek/x-wrt/staging_dir/host/include  -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libdecnumber -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libdecnumber/dpd -I../libdecnumber -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libbacktrace   -o gimple-match.o -MT gimple-match.o -MMD -MP -MF ./.deps/gimple-match.TPo gimple-match.c
g++  -fno-PIE -c   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings  -Wno-unused -DHAVE_CONFIG_H -I. -I. -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/. -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../include -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libcpp/include -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libcody -I/home/etek/x-wrt/staging_dir/host/include -I/home/etek/x-wrt/staging_dir/host/include -I/home/etek/x-wrt/staging_dir/host/include  -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libdecnumber -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libdecnumber/dpd -I../libdecnumber -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libbacktrace   -o generic-match.o -MT generic-match.o -MMD -MP -MF ./.deps/generic-match.TPo generic-match.c
g++  -fno-PIE -c   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/. -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../include -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libcpp/include -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libcody -I/home/etek/x-wrt/staging_dir/host/include -I/home/etek/x-wrt/staging_dir/host/include -I/home/etek/x-wrt/staging_dir/host/include  -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libdecnumber -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libdecnumber/dpd -I../libdecnumber -I/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/../libbacktrace   -o insn-attrtab.o -MT insn-attrtab.o -MMD -MP -MF ./.deps/insn-attrtab.TPo insn-attrtab.c
build/genautomata /home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/common.md /home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/config/mips/mips.md \
  insn-conditions.md > tmp-automata.c
/bin/bash: line 1:  9244 Killed                  build/genautomata /home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/common.md /home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0/gcc/config/mips/mips.md insn-conditions.md > tmp-automata.c
Makefile:2459: recipe for target 's-automata' failed
make[5]: *** [s-automata] Error 137
make[5]: Leaving directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/gcc'
Makefile:4416: recipe for target 'all-gcc' failed
make[4]: *** [all-gcc] Error 2
make[4]: Leaving directory '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial'
Makefile:36: recipe for target '/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/.built' failed
make[3]: *** [/home/etek/x-wrt/build_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/gcc-11.2.0-initial/.built] Error 2
make[3]: Leaving directory '/home/etek/x-wrt/toolchain/gcc/initial'
time: toolchain/gcc/initial/compile#198.94#33.15#304.82
    ERROR: toolchain/gcc/initial failed to build.
toolchain/Makefile:95: recipe for target 'toolchain/gcc/initial/compile' failed
make[2]: *** [toolchain/gcc/initial/compile] Error 1
make[2]: Leaving directory '/home/etek/x-wrt'
toolchain/Makefile:93: recipe for target '/home/etek/x-wrt/staging_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/stamp/.toolchain_compile' failed
make[1]: *** [/home/etek/x-wrt/staging_dir/toolchain-mipsel_24kc_gcc-11.2.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/etek/x-wrt'
/home/etek/x-wrt/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by Y32Gcnte8z** [comment]
我也遇到这个
