### ISSUE TITLE
Fake mesh service

### ISSUE THREAD

**Issue by godshades** [x-wrt/x-wrt#225]
Execute me sir, can you help me how to use Fake mesh service
Does it same 802.11r ?
Sr I can't find any document about this service

**Comment by ptpt52** [comment]
for now fakemesh works mostly
docs: https://github.com/x-wrt/com.x-wrt/blob/master/luci-app-fakemesh/README.md

**Comment by ptpt52** [comment]
@godshades  see https://github.com/x-wrt/com.x-wrt/blob/master/luci-app-fakemesh/README.md

**Comment by godshades** [comment]
Hi please update description about fronthaul
