### ISSUE TITLE
x-wrt系统重启时，电脑会接收到上级dhcp分配的ip

### ISSUE THREAD

**Issue by wxm5188** [x-wrt/x-wrt#234]
**x-wrt系统重启时，电脑会接收到上级dhcp分配的ip**

当x-wrt路由设置为二级路由器时（WAN接上级LAN）：
x-wrt重启，或者电脑先开机，而x-wrt后通电时，电脑ip会接收到上级DHCP的ip和网关信息，导致无法联网。

刷机路由为“小米路由器3（MT7620A）”
[Powered by LuCI Master (git-22.080.59999-6aa3a7b)](https://github.com/openwrt/luci) / X-WRT 22.02_b202203220050 Jammy r0+19344-4a8f4ea2cd

**Comment by ptpt52** [comment]
非常正常，没啥问题，动动你的小手拔掉网线再插上就是了
