### ISSUE TITLE
请教下Natflow和HWNAT

### ISSUE THREAD

**Issue by DoveKi** [x-wrt/x-wrt#236]
高级选项里的Natflow默认是开启的，防火墙里的路由/NAT 分载两个选项默认是关闭的
请问两个能同时开启么，同时打开效果会冲突还是会更好
是mt7621设备
@ptpt52

**Comment by ptpt52** [comment]
`防火墙里的路由/NAT 分载` 不用开，开了也没有用，这个开了在x-wrt不会有任何作用

**Comment by DoveKi** [comment]
> `防火墙里的路由/NAT 分载` 不用开，开了也没有用，这个开了在x-wrt不会有任何作用

好的谢谢回复
