### ISSUE TITLE
ipq806x系补丁错误，请修复

### ISSUE THREAD

**Issue by Hiyajomaho-num9** [x-wrt/x-wrt#249]
编译错误日志为

> Applying /home/th1996/Openwrt_SDE/4g/x-wrt/target/linux/ipq806x/patches-5.10/0069-arm-boot-add-dts-files.patch using plaintext: 
patching file arch/arm/boot/dts/Makefile
patch unexpectedly ends in middle of line
patch: **** malformed patch at line 43:  
Patch failed!  Please fix /home/th1996/Openwrt_SDE/4g/x-wrt/target/linux/ipq806x/patches-5.10/0069-arm-boot-add-dts-files.patch!
make[4]: *** [Makefile:37: /home/th1996/Openwrt_SDE/4g/x-wrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-5.10.113/.prepared_be3317cae0b61861d05ce2360e2f719a] Error 1
make[4]: Leaving directory '/home/th1996/Openwrt_SDE/4g/x-wrt/target/linux/ipq806x'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/th1996/Openwrt_SDE/4g/x-wrt/target/linux'
time: target/linux/compile#7.18#3.77#9.02
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1

经过排查，为ipq806x/patch-5.10/0069-arm-boot-add-dts-files.patch文件错误
错误位置为
`--- a/arch/arm/boot/dts/Makefile`
`+++ b/arch/arm/boot/dts/Makefile`
`@@ -908,8 +908,30 @@ dtb-$(CONFIG_ARCH_QCOM) += \`

下列为8个增添到31个，但实际上只增添30个导致编译报错，应改为

`@@ -908,8 +908,31 @@ dtb-$(CONFIG_ARCH_QCOM) += \`

鄙人不善于使用github，恳请作者修复该错误

**Comment by ptpt52** [comment]
master 分支不一定能编译过，这个修改 正如你说要改成31
编译教程看 https://blog.x-wrt.com/docs/build/
