### ISSUE TITLE
List support DAWN

### ISSUE THREAD

**Issue by godshades** [x-wrt/x-wrt#256]
Hi, I have newifi 3d2 and xiaomi redmi ac2100
Both install latest version
In Redmi  router I have found DAWN menu, but 3d2 no
Where I can find list of your support DAWN, Thanks

**Comment by ptpt52** [comment]
DAWN was drop since

**Comment by godshades** [comment]
is it not good or use fake mesh is better ?

and 3d2 vs redmi ac2100, which is better, in my country this is same price
may i know your opinion
or another suggest, I can buy from taobao ~110¥

**Comment by ptpt52** [comment]
okay, dawn would be introduce again in new release version: `v22.03_b202206101526`
this should co-work with fakemesh
