### ISSUE TITLE
AP mode

### ISSUE THREAD

**Issue by godshades** [x-wrt/x-wrt#257]
Hi, can we have ap mode in setting
normally I turn off dhcp for each AP, but after reboot it will turn on by default
any ideal for this ?

**Comment by ptpt52** [comment]
it should not turn on after reboot
maybe your device cannot save cofnig?

**Comment by godshades** [comment]
@ptpt52 any other config can save, only dhcp in lan setting can't
my list ap is: redmi ac2100, mi mini, mi r4ac 100mb
all can't :(

**Comment by ptpt52** [comment]
maybe you could use fakemesh to setup your network.

**Comment by godshades** [comment]
now my setup is newifi 3d2 (DHCP) => lan - lan each AP (turn off dhcp)
if using fakemesh, i can setup lan-wan each AP and don't need turn off dhcp each ap right ?

**Comment by ptpt52** [comment]
fakemesh would handle dhcp, it would help to turn it off, and make wan  work as lan

**Comment by godshades** [comment]
Hi, after turn on fake mesh
My router not assign ip (lan & wireless) so now i can't do anything
The wifi list still display new ssid when I create fake mesh but can't connected

**Comment by ptpt52** [comment]
your setup must have one AC and one or mor AP
AP.....AP-----AC---

and
AC: set fakemesh role AC,

AP: set fakemesh role wired AP or Agent (if you use wifi to connected to AC)

**Comment by godshades** [comment]
Yes, I just set newifi d2 to role ac then this happen like above

**Comment by godshades** [comment]
after go to failure mode, I can config and make it work
still don't know what is real problem

**Comment by godshades** [comment]
work great
and i found DAWN work better than usteer
