### ISSUE TITLE
如何修改ESSID

### ISSUE THREAD

**Issue by da1rre1n** [x-wrt/x-wrt#27]
查阅网上很多方法均没有修改成功？？

我的路由器型号：Xiaomi Mi Router R3
架构：MediaTek MT7620A ver:2 eco:6
固件版本：NATCAP 4.0_b201810261006 Bionic r8426-94148f6b45
内核版本：4.14.78

试过在/etc/config/wireless文件中，在相应的 ssid 行后添加一行 bssid option，保存重启后发现还是没能修改成功

**Comment by ptpt52** [comment]
@da1rre1n 升级最新版本，设置向导 页面设置，或者无线页面修改。

**Comment by da1rre1n** [comment]
> @da1rre1n 升级最新版本，设置向导 页面设置，或者无线页面修改。

好的，谢谢
