### ISSUE TITLE
WEB界面不显示软件包管理

### ISSUE THREAD

**Issue by jjm2473** [x-wrt/x-wrt#277]
是否因为使用了admin用户登陆WEB界面？为啥root用户无法登陆WEB界面？

**Comment by ptpt52** [comment]
界面默认 admin/admin
ssh默认 root/admin

**Comment by jjm2473** [comment]
我是说web界面怎么没有“软件包”这个菜单？

**Comment by jjm2473** [comment]
我用 `opkg install luci-app-opkg` 提示已经安装了

**Comment by jjm2473** [comment]
OK，找到原因了，一开始设置错了软件源，然后执行安装 `luci-app-opkg`，安装失败了，但是 opkg 却把版本号记录到 status 文件里，修复软件源之后，再次执行安装 `luci-app-opkg`，opkg会认为线上的软件仓库里面的`luci-app-opkg`版本更旧，于是总是安装失败。解决方法是删掉 status 文件里面的记录再安装
