### ISSUE TITLE
Netgear WAX202

### ISSUE THREAD

**Issue by bruh1k** [x-wrt/x-wrt#283]
Hey X-WRT developers! Do you have plans to add support to Netgear WAX202 in the future? It uses MTK 7621 processor and is quite a deal on amazon for USD 30. Any response would be very appreciated!!!!

**Comment by ptpt52** [comment]
you could build it from source
https://blog.x-wrt.com/docs/build/

anyway I would pack it in next release.

**Comment by bruh1k** [comment]
Thanks for the info!!! I will look into that.
