### ISSUE TITLE
Xiaomi Redmi Router AX6000 “Network device 'pppoe-wan' link is down”

### ISSUE THREAD

**Issue by zixiang5288** [x-wrt/x-wrt#284]
请教：
版本：x-wrt-22.03-b202209270703
反馈问题：大流量上传时出现“Network device 'pppoe-wan' link is down”，同场景多次重现
系统日志如下：
Thu Sep 29 18:10:31 2022 daemon.warn odhcpd[2795]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Thu Sep 29 18:11:00 2022 daemon.notice hostapd: wlan0: STA-OPMODE-SMPS-MODE-CHANGED a8:7e:ea:ee:4e:59 dynamic
Thu Sep 29 18:11:01 2022 daemon.warn odhcpd[2795]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Thu Sep 29 18:11:19 2022 daemon.notice hostapd: wlan0: STA-OPMODE-SMPS-MODE-CHANGED a8:7e:ea:ee:4e:59 off
Thu Sep 29 18:13:33 2022 daemon.info pppd[18163]: No response to 5 echo-requests
Thu Sep 29 18:13:33 2022 daemon.notice pppd[18163]: Serial link appears to be disconnected.
Thu Sep 29 18:13:33 2022 daemon.info pppd[18163]: Connect time 645.7 minutes.
Thu Sep 29 18:13:33 2022 daemon.info pppd[18163]: Sent 3154041685 bytes, received 162583373 bytes.
Thu Sep 29 18:13:33 2022 daemon.warn dnsmasq[7040]: failed to create listening socket for fe80::ae4e:91ff:fe64:9c4f%pppoe-wan: Address not available
Thu Sep 29 18:13:33 2022 daemon.warn dnsmasq[7040]: failed to create listening socket for fe80::ae4e:91ff:fe64:9c4f%pppoe-wan: Address not available
Thu Sep 29 18:13:33 2022 daemon.notice netifd: Network device 'pppoe-wan' link is down
Thu Sep 29 18:13:33 2022 daemon.notice netifd: Network alias 'pppoe-wan' link is down
Thu Sep 29 18:13:33 2022 daemon.notice netifd: Interface 'wan_6' has link connectivity loss
Thu Sep 29 18:13:33 2022 daemon.notice netifd: Interface 'wan' has lost the connection
Thu Sep 29 18:13:33 2022 daemon.warn dnsmasq[7040]: no servers found in /tmp/resolv.conf.d/resolv.conf.auto, will retry
Thu Sep 29 18:13:33 2022 user.notice mwan3-hotplug[11961]: mwan3 hotplug on wan not called because interface disabled
Thu Sep 29 18:13:33 2022 daemon.err odhcp6c[18921]: Failed to send SOLICIT message to ff02::1:2 (Network unreachable)
Thu Sep 29 18:13:33 2022 daemon.notice netifd: Interface 'wan_6' is now down
Thu Sep 29 18:13:33 2022 daemon.notice netifd: Interface 'wan_6' is disabled
Thu Sep 29 18:13:33 2022 user.notice mwan3-hotplug[12098]: mwan3 hotplug on wan not called because interface disabled
Thu Sep 29 18:13:36 2022 kern.info kernel: [63468.777969] mt7530 mdio-bus:1f lan3: Link is Down
Thu Sep 29 18:13:36 2022 kern.info kernel: [63468.782735] br-lan: port 3(lan3) entered disabled state
Thu Sep 29 18:13:36 2022 daemon.notice netifd: Network device 'lan3' link is down
Thu Sep 29 18:13:38 2022 daemon.err miniupnpd[9016]: resolve_stun_host: getaddrinfo(stun.miwifi.com, 3478, ...) failed : Try again
Thu Sep 29 18:13:38 2022 daemon.err miniupnpd[9016]: STUN: Performing STUN failed: Host is unreachable
Thu Sep 29 18:13:39 2022 daemon.notice pppd[18163]: Connection terminated.
Thu Sep 29 18:13:39 2022 daemon.info pppd[18163]: Connect time 645.7 minutes.
Thu Sep 29 18:13:39 2022 daemon.info pppd[18163]: Sent 3154041685 bytes, received 162583373 bytes.
Thu Sep 29 18:13:39 2022 kern.warn kernel: [63471.235530] warning: catch unregister event for dev=pppoe-wan
Thu Sep 29 18:13:39 2022 kern.debug kernel: [63471.241278] {natflow}:natflow_netdev_event(): catch NETDEV_UNREGISTER event for dev=pppoe-wan
Thu Sep 29 18:13:39 2022 daemon.notice pppd[18163]: Modem hangup
Thu Sep 29 18:13:39 2022 daemon.info pppd[18163]: Exit.
Thu Sep 29 18:13:39 2022 daemon.notice netifd: Interface 'wan' is now down
Thu Sep 29 18:13:39 2022 daemon.notice netifd: Interface 'wan' is setting up now
Thu Sep 29 18:13:39 2022 daemon.info pppd[12576]: Plugin pppoe.so loaded.
Thu Sep 29 18:13:39 2022 daemon.info pppd[12576]: PPPoE plugin from pppd 2.4.9
Thu Sep 29 18:13:39 2022 daemon.notice pppd[12576]: pppd 2.4.9 started by root, uid 0
Thu Sep 29 18:13:54 2022 daemon.warn pppd[12576]: Timeout waiting for PADO packets
Thu Sep 29 18:13:54 2022 daemon.err pppd[12576]: Unable to complete PPPoE Discovery
Thu Sep 29 18:13:54 2022 daemon.info pppd[12576]: Exit.
Thu Sep 29 18:13:54 2022 daemon.notice netifd: Interface 'wan' is now down
Thu Sep 29 18:13:54 2022 daemon.notice netifd: Interface 'wan' is setting up now
Thu Sep 29 18:13:54 2022 daemon.info pppd[13256]: Plugin pppoe.so loaded.
Thu Sep 29 18:13:54 2022 daemon.info pppd[13256]: PPPoE plugin from pppd 2.4.9
Thu Sep 29 18:13:54 2022 daemon.notice pppd[13256]: pppd 2.4.9 started by root, uid 0
Thu Sep 29 18:14:09 2022 daemon.warn pppd[13256]: Timeout waiting for PADO packets
Thu Sep 29 18:14:09 2022 daemon.err pppd[13256]: Unable to complete PPPoE Discovery
Thu Sep 29 18:14:09 2022 daemon.info pppd[13256]: Exit.
Thu Sep 29 18:14:09 2022 daemon.notice netifd: Interface 'wan' is now down
Thu Sep 29 18:14:09 2022 daemon.notice netifd: Interface 'wan' is setting up now
Thu Sep 29 18:14:09 2022 daemon.info pppd[13933]: Plugin pppoe.so loaded.
Thu Sep 29 18:14:09 2022 daemon.info pppd[13933]: PPPoE plugin from pppd 2.4.9
Thu Sep 29 18:14:09 2022 daemon.notice pppd[13933]: pppd 2.4.9 started by root, uid 0
Thu Sep 29 18:14:24 2022 daemon.warn pppd[13933]: Timeout waiting for PADO packets
Thu Sep 29 18:14:25 2022 daemon.err pppd[13933]: Unable to complete PPPoE Discovery
Thu Sep 29 18:14:25 2022 daemon.info pppd[13933]: Exit.
Thu Sep 29 18:14:25 2022 daemon.notice netifd: Interface 'wan' is now down
Thu Sep 29 18:14:25 2022 daemon.notice netifd: Interface 'wan' is setting up now
Thu Sep 29 18:14:25 2022 daemon.info pppd[14617]: Plugin pppoe.so loaded.
Thu Sep 29 18:14:25 2022 daemon.info pppd[14617]: PPPoE plugin from pppd 2.4.9
Thu Sep 29 18:14:25 2022 daemon.notice pppd[14617]: pppd 2.4.9 started by root, uid 0
Thu Sep 29 18:14:40 2022 daemon.warn pppd[14617]: Timeout waiting for PADO packets
Thu Sep 29 18:14:40 2022 daemon.err pppd[14617]: Unable to complete PPPoE Discovery
Thu Sep 29 18:14:40 2022 daemon.info pppd[14617]: Exit.
Thu Sep 29 18:14:40 2022 daemon.notice netifd: Interface 'wan' is now down
Thu Sep 29 18:14:40 2022 daemon.notice netifd: Interface 'wan' is setting up now
Thu Sep 29 18:14:40 2022 daemon.info pppd[15294]: Plugin pppoe.so loaded.
Thu Sep 29 18:14:40 2022 daemon.info pppd[15294]: PPPoE plugin from pppd 2.4.9
Thu Sep 29 18:14:40 2022 daemon.notice pppd[15294]: pppd 2.4.9 started by root, uid 0
Thu Sep 29 18:14:55 2022 daemon.warn pppd[15294]: Timeout waiting for PADO packets
Thu Sep 29 18:14:55 2022 daemon.err pppd[15294]: Unable to complete PPPoE Discovery
Thu Sep 29 18:14:55 2022 daemon.info pppd[15294]: Exit.
Thu Sep 29 18:14:55 2022 daemon.notice netifd: Interface 'wan' is now down
Thu Sep 29 18:14:55 2022 daemon.notice netifd: Interface 'wan' is setting up now
Thu Sep 29 18:14:55 2022 daemon.info pppd[15977]: Plugin pppoe.so loaded.
Thu Sep 29 18:14:55 2022 daemon.info pppd[15977]: PPPoE plugin from pppd 2.4.9
Thu Sep 29 18:14:55 2022 daemon.notice pppd[15977]: pppd 2.4.9 started by root, uid 0
Thu Sep 29 18:15:01 2022 daemon.err uwsgi[4679]: *** has_emperor mode detected (fd: 7) ***
Thu Sep 29 18:15:01 2022 daemon.err uwsgi[4679]: [uWSGI] getting INI configuration from /etc/uwsgi/vassals/luci-webui.ini
Thu Sep 29 18:15:01 2022 daemon.err uwsgi[4679]: Thu Sep 29 18:15:01 2022 - [emperor] vassal /etc/uwsgi/vassals/luci-webui.ini has been spawned
Thu Sep 29 18:15:01 2022 daemon.err uwsgi[4679]: Thu Sep 29 18:15:01 2022 - [emperor] vassal /etc/uwsgi/vassals/luci-webui.ini is ready to accept requests
Thu Sep 29 18:15:01 2022 daemon.info uwsgi-luci: spawned uWSGI master process (pid: 16472)
Thu Sep 29 18:15:01 2022 daemon.err uwsgi[4679]: Thu Sep 29 18:15:01 2022 - [emperor] vassal /etc/uwsgi/vassals/luci-webui.ini is now loyal
Thu Sep 29 18:15:06 2022 user.info : luci: accepted login on /admin/dashboard for admin from 10.0.0.249
Thu Sep 29 18:15:10 2022 daemon.warn pppd[15977]: Timeout waiting for PADO packets
Thu Sep 29 18:15:11 2022 daemon.err pppd[15977]: Unable to complete PPPoE Discovery
Thu Sep 29 18:15:11 2022 daemon.info pppd[15977]: Exit.
Thu Sep 29 18:15:11 2022 daemon.notice netifd: Interface 'wan' is now down
Thu Sep 29 18:15:11 2022 daemon.notice netifd: Interface 'wan' is setting up now
Thu Sep 29 18:15:11 2022 daemon.info pppd[16887]: Plugin pppoe.so loaded.
Thu Sep 29 18:15:11 2022 daemon.info pppd[16887]: PPPoE plugin from pppd 2.4.9
Thu Sep 29 18:15:11 2022 daemon.notice pppd[16887]: pppd 2.4.9 started by root, uid 0
Thu Sep 29 18:15:22 2022 daemon.err uwsgi[4679]: *** has_emperor mode detected (fd: 8) ***
Thu Sep 29 18:15:22 2022 daemon.err uwsgi[4679]: [uWSGI] getting INI configuration from /etc/uwsgi/vassals/luci-cgi_io.ini
Thu Sep 29 18:15:22 2022 daemon.err uwsgi[4679]: Thu Sep 29 18:15:22 2022 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini has been spawned
Thu Sep 29 18:15:22 2022 daemon.err uwsgi[4679]: Thu Sep 29 18:15:22 2022 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini is ready to accept requests

**Comment by ptpt52** [comment]
系统，高级设置，关闭硬件转发和natflow，看看还有问题嘛？ @zixiang5288

**Comment by zixiang5288** [comment]
关闭硬件加速后至今暂未出现wan口断网，感谢！

**Comment by ptpt52** [comment]
> 关闭硬件加速后至今暂未出现wan口断网，感谢！

建议等下一个版本再测试下 开启硬件转发的情况。

**Comment by zixiang5288** [comment]
好的，收到！

**Comment by zixiang5288** [comment]
版本：x-wrt-22.03-b202210011001
设置：默认，打开硬件转发和natflow
测试：大流量下载，上传暂未出现wan口断网，稳定运行11小时

感谢辛苦付出，让固件不断完善！

**Comment by zixiang5288** [comment]
版本：x-wrt-22.03-b202210011001
暂时丢包有点多，时不时地断流

**Comment by ptpt52** [comment]
如何丢包，如何断流，怎么判断？

**Comment by zixiang5288** [comment]
抱歉，是我开upnp的原因，开了upnp之后有时浏览网页需要重新刷新一下，我就在命令行ping了一下路由ip，不定时出现超时，关闭upnp后未出现超时现象，又用软件试了下，好很多了
![QQ图片20221002085423](https://user-images.githubusercontent.com/83002461/193433590-13231681-cf89-45d8-8d15-7123220a0c11.png)

**Comment by ptpt52** [comment]
开UPNP和断流有啥关系呢？
