### ISSUE TITLE
红米ax6000 自己编译能成功，但是web界面打不开。

### ISSUE THREAD

**Issue by iseeyou** [x-wrt/x-wrt#285]
原版功能太少，所以自己试着编译。
选择好红米ax6000加了几个插件，结果web界面打不开。
ssh还是可以上去。
按教程 先刷了 initramfs-factory.ubi 然后升级 sysupgrade.bin

**Comment by ptpt52** [comment]
严格按照教程来编译 https://blog.x-wrt.com/docs/build/
然后再在此基础修改配置编译。

**Comment by JAM2199562** [comment]
看看这几个设置
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_uhttpd-mod-ubus=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
CONFIG_LUCI_LANG_zh_Hans=y
