### ISSUE TITLE
x86-generic 增加网卡驱动 Qualcomm Atheros Attansic L2 Fast Ethernet (rev a0)

### ISSUE THREAD

**Issue by jerryzhu0713** [x-wrt/x-wrt#29]
能否增加以下网卡驱动
lspci里能看到以下网卡，但是无法驱动
Qualcomm Atheros Attansic L2 Fast Ethernet (rev a0)
能否增加相关驱动
谢谢

**Comment by ptpt52** [comment]
已支持，可以自行编译，下个版本有。
https://github.com/x-wrt/com.x-wrt/commit/f940912d4e5262371c26a0b8350ddfaa4b5e605c
