### ISSUE TITLE
10月12日版本的 CSAC固件无法保存设置

### ISSUE THREAD

**Issue by mrlong32** [x-wrt/x-wrt#291]
ping ttl返回是128
任何配置修改均无效

**Comment by ptpt52** [comment]
@mrlong32  登录ssh，执行 df -h 看看空间剩余情况。

**Comment by mrlong32** [comment]
无法登录，SSH默认关闭
因无法保存配置
打开操作无效

**Comment by ptpt52** [comment]
刷新版本看看。

**Comment by mrlong32** [comment]
> 刷新版本看看。

刷了，还是不行，是不是分区不一样了
从挂载点看 /overlay 才300K

**Comment by ptpt52** [comment]
df -h 看看

**Comment by mrlong32** [comment]
> df -h 看看

打不开SSH，没法进命令行

**Comment by ptpt52** [comment]
@mrlong32 
用这个版本试试，固件删了部分软件留出空间
http://downloads.x-wrt.com/rom/Downloads/csac2/

**Comment by mrlong32** [comment]
> @mrlong32 用这个版本试试，固件删了部分软件留出空间 http://downloads.x-wrt.com/rom/Downloads/csac2/

OK了，这个恢复正常了，谢谢

**Comment by ptpt52** [comment]
df -h 看看。

**Comment by mrlong32** [comment]
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 9.0M      9.0M         0 100% /rom
devtmpfs                 58.9M         0     58.9M   0% /rom/dev
tmpfs                    59.5M    444.0K     59.0M   1% /tmp
/dev/mtdblock11           4.4M    368.0K      4.1M   8% /overlay
overlayfs:/overlay        4.4M    368.0K      4.1M   8% /
tmpfs                     1.0M         0      1.0M   0% /mnt
tmpfs                   512.0K         0    512.0K   0% /dev
