### ISSUE TITLE
AX6000 升级X-WRT 固件

### ISSUE THREAD

**Issue by sailingchen** [x-wrt/x-wrt#293]
您好， 请问红米AX6000 刷了 10.22 的 固件，想一直更新固件的话，是不是直接刷 **squashfs-sysupgrade.bin** 就可以了。
**不用刷   initramfs-factory.ubi 再刷 squashfs-sysupgrade.bin 。
不用刷回官方固件再跑一次刷机流程。**

**Comment by ptpt52** [comment]
界面升级squashfs-sysupgrade.bin就可以。

**Comment by sailingchen** [comment]
@ptpt52  谢谢
