### ISSUE TITLE
能否支持一下京东云一代，mt7621 32m + 512，谢谢

### ISSUE THREAD

**Issue by mrxyzhang** [x-wrt/x-wrt#294]

**Comment by mrxyzhang** [comment]
具体的型号为 JDC RE-SP-01B,

**Comment by ptpt52** [comment]
无法支持，没有信息。

**Comment by Super-member** [comment]
> 无法支持，没有信息。

大佬 隔壁已经有了 能不添加下谢谢   
https://github.com/immortalwrt/immortalwrt/blob/openwrt-21.02/target/linux/ramips/dts/mt7621_jdcloud_re-sp-01b.dts

**Comment by Super-member** [comment]
> 如何刷机？可以不拆刷吗？

2.3.14以下版本可以，最新版得用编译器
