### ISSUE TITLE
需要诺基亚贝尔 A-040W-Q固件支持

### ISSUE THREAD

**Issue by 363843342** [x-wrt/x-wrt#296]
目前已经有第三方编译openwrt适配，详见https://www.right.com.cn/FORUM/thread-5541199-1-1.html。
但是没有mwan3多拨，利用opkg装上去多拨也是失效

硬件配置信息如下：
CPU: MediaTek MT7621A
WIFI: MT7615DN,  2.4G(2T2R),  5G(2T2R)。 无PA和LNA。
MEM: DDR3-256M:  
闪存： NAND FLASH 128M

**Comment by 363843342** [comment]
相关的GPIO信息如下：
GPIO BUTTON:
WIFI: #7
无线对码: #18
RESET: #15

GPIO LED:
无线1: #4
无线2: #3
USB: #13 (ACTIVE_LOW)

**Comment by ptpt52** [comment]
不是很有名的设备，而且没有比较好的刷机手段，7621设备太多了，暂不考虑。

**Comment by ptpt52** [comment]
支持了。
