### ISSUE TITLE
无法安装openconnect  内核版本不兼容

### ISSUE THREAD

**Issue by woaihuangfan** [x-wrt/x-wrt#299]
尝试安装时遇到以下错误：
```
root@X-WRT:/mnt/sda1# opkg install openconnect
Installing openconnect (9.01-1) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages/openconnect_9.01-1_mipsel_24kc.ipk
Configuring openconnect.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.155-1-8057c73633ced5b3fb73547a26b81aa2) for kmod-tun
```

可以帮忙看一下吗

为了安装openconnect, 我尝试自己编译一个，但是make 时遇到下面的错误

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24730837/203981925-8ff788fe-85e9-4e6d-b094-6128edd595b0.png">
编译环境：Macos M1 Apple silicon

有哪位同学有在M1 mac下成功编译过吗

**Comment by ptpt52** [comment]
强制安装就行 
```
opkg install --force-depends openconnect
```
不需要另外安装所谓kmod-tun
系统自带有。

**Comment by sukianata** [comment]
@ptpt52 感谢回复

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
