### ISSUE TITLE
挂载RTL8188EU弄了许久都没有成功

### ISSUE THREAD

**Issue by orochix1** [x-wrt/x-wrt#30]
想编译一下发现包里也没有8188eu的驱动。

**Comment by orochix1** [comment]
不能安装驱动？
root@X-WRT:~# opkg install kmod-rtl8187
Unknown package 'kmod-rtl8187'
Collected errors:
 * opkg_install_cmd: Cannot install package kmod-rtl8187..

**Comment by ptpt52** [comment]
x86系列是有的，但是其他芯片，需要自己编译呀。
