### ISSUE TITLE
tp的6088会支持吗？

### ISSUE THREAD

**Issue by xh0823** [x-wrt/x-wrt#300]
tp的6088大佬会开发吗？

**Comment by ptpt52** [comment]
tplink不太可能，就算有固件你也刷不进去吧。不拆机难

**Comment by xh0823** [comment]
> tplink不太可能，就算有固件你也刷不进去吧。不拆机难

嗯 lean那边好像可以 顺便问问是硬路由好一点还是软路由好一点

**Comment by ptpt52** [comment]
> > tplink不太可能，就算有固件你也刷不进去吧。不拆机难
> 
> 嗯 lean那边好像可以 顺便问问是硬路由好一点还是软路由好一点

可以？ 怎么刷机，拆开串口刷吗？串口也无法输入吧？

软路由，硬路由在我看来，没啥区别，硬路由带Wi-Fi方便点。

**Comment by xh0823** [comment]
> > > tplink不太可能，就算有固件你也刷不进去吧。不拆机难
> > 
> > 
> > 嗯瘦那一边好像可以顺便问是硬路由好一点还是软路由好一点
> 
> 可以吗？ 怎么刷机，拆开串口刷吗？串口也无法输入吧？
> 
> 软路由，硬路由在我看来，没有啥区，硬路由带Wi-Fi方方便点。

好的 感谢您的回复
