### ISSUE TITLE
希望支持树莓派

### ISSUE THREAD

**Issue by linxuankent** [x-wrt/x-wrt#31]
希望支持树莓派

**Comment by ptpt52** [comment]
具体要哪一个型号？英文。

**Comment by linxuankent** [comment]
Raspberry Pi 3B+

**Comment by linxuankent** [comment]
> 具体要哪一个型号？英文。

Raspberry Pi 3B +

**Comment by ptpt52** [comment]
下一个版本支持

**Comment by richcup** [comment]
希望 树莓派 Pi 4 SSR  支持 !!!

**Comment by ptpt52** [comment]
@richcup 请自己想办法自己编译，可以用SDK编译，或者源代码编译。这里不提供。

**Comment by richcup** [comment]
感謝板主回覆
我試用過三個树莓派 Pi4 版本這個版本是最好最穩定非常感謝!!!! 
網上已經找不到關於SSR更加詳細的說明及資料來源 ( 原因不詳? )
自己無法編譯也沒能力 ( shadowsocksr-libev-alt ,  shadowsocksr-libev-server , shadowsocksr-libev-ssr-local )  這三個檔案要如何製作出來?  可以的話說明一下
非常感謝
