### ISSUE TITLE
求支持 AX6000的 HWNAT驱动

### ISSUE THREAD

**Issue by ghost** [x-wrt/x-wrt#318]
### Describe the bug

https://www.right.com.cn/forum/thread-8261104-1-1.html
https://github.com/padavanonly/immortalwrtARM/commit/e23e9cd62fe82955618f215411bdbbea93495557

### OpenWrt version

X-WRT 22.10_b202212230054 Kinetic / LuCI (no branch) branch git-22.356.59859-a3abce8

### OpenWrt target/subtarget

X-WRT 22.10_b202212230054 Kinetic / LuCI (no branch) branch git-22.356.59859-a3abce8

### Device

AX6000

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ptpt52** [comment]
不知道你理解存在什么问题，x-wrt 自带自己的hwnat
