### ISSUE TITLE
XIaomi R3 

### ISSUE THREAD

**Issue by wohenbushuang** [x-wrt/x-wrt#33]
i can find that X-wrt used to support Xiaomi R3 in #20 , but now i cannot find R3 firmware download link on X-wrt website. there are only latest version firmwares on X-wrt website download page.

i dont know what's the reason you choose to abandon R3, but at least i request for a history version plz

**Comment by ptpt52** [comment]
see  https://github.com/x-wrt/x-wrt/issues/6
where you can find the download location
mir3 is never abandon..

**Comment by erenkan** [comment]
is the X-wrt working on Mi router 3 without any bug? I mean is it stable as stock and openwrt? Is there any guide to flash x-wrt? Thanks
