### ISSUE TITLE
希望大佬能为红米AX6000再添加一个只使用单分区的布局的版本

### ISSUE THREAD

**Issue by DoveKi** [x-wrt/x-wrt#332]
像早期的AX3600这种和官方固件分区布局一样只使用ubi0或者ubi1
通过flag_boot_rootfs和flag_last_success切换启动分区实现双系统共存
30M单分区对于插件不多情况下完全够用了，留着用另一个分区使用官方固件或者测试新固件很方便

最新AX3600的主线分区布局也是和现在AX6000一样同时使用两个分区，天灵在基础上添加了一个旧版单分区布局
https://github.com/1715173329/imoutowrt/commit/6a01a7b07b7459ac3ae54544c83a7aa68913343d
我不懂dts改不来 希望大佬能添加一个这种布局的版本
@ptpt52

**Comment by ptpt52** [comment]
@DoveKi  不会再添加其他布局版本了，如果需要研究双系统，可以自行添加吧。这些我们一般用不着，开发需要代价。
