### ISSUE TITLE
Ruijie RG-MTFi-M520 LAN port not working

### ISSUE THREAD

**Issue by mrkenz9595** [x-wrt/x-wrt#352]
### Describe the bug

Ruijie RG-MTFi-M520 LAN port not working, please help

### OpenWrt version

23.10_b202311242121

### OpenWrt release

23.10_b202311242121

### OpenWrt target/subtarget

23.10_b202311242121

### Device

Ruijie RG-MTFi-M520

### Image kind

Official downloaded image

### Terms

- [ ] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ptpt52** [comment]
@mrkenz9595 great, I am gona fix the issue.

**Comment by ptpt52** [comment]
@mrkenz9595 
try the firmware and test again
`https://downloads.x-wrt.com/rom/Downloads/ipq806x/`

**Comment by mrkenz9595** [comment]
@ptpt52 working ! Thanks you very much.
