### ISSUE TITLE
xiaomi mini no 2.4 wireless

### ISSUE THREAD

**Issue by godshades** [x-wrt/x-wrt#353]
### Describe the bug

Hi i just flash latest version for xiaomi mini but 2.4 band has gone. 5 ghz band max tx power is 3dbm, please help
![Screenshot_2023-12-02-21-11-15-790_org mozilla firefox](https://github.com/x-wrt/x-wrt/assets/12244851/6e8c430c-12b2-49aa-99f0-74ddbf97d255)

### OpenWrt version

latest

### OpenWrt release

latest

### OpenWrt target/subtarget

mips

### Device

xiaomi mini

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ptpt52** [comment]
@godshades 
I am gona post a new firmware here, please test.

**Comment by ptpt52** [comment]
try:
https://downloads.x-wrt.com/rom/Downloads/x-wrt-23.10-b202312030808-ramips-mt7620-xiaomi_miwifi-mini-squashfs-sysupgrade.bin

**Comment by godshades** [comment]
@ptpt52 breaked (steady orange) :(

**Comment by ptpt52** [comment]
again, try the new one: https://downloads.x-wrt.com/rom/Downloads/x-wrt-23.10-b202312031209-ramips-mt7620-xiaomi_miwifi-mini-squashfs-sysupgrade.bin

**Comment by godshades** [comment]
@ptpt52 after breaked, when come safe mode to flash miwifi, my router is red light, i think it's dead...
i'm finding way to fix this

**Comment by godshades** [comment]
i have buy new mini and the lastest fw work
anyone know how to fix the steady red light please ping me
