### ISSUE TITLE
Unknown UDP Connection

### ISSUE THREAD

**Issue by TobiKi400** [x-wrt/x-wrt#363]
![grafik](https://github.com/x-wrt/x-wrt/assets/147280037/b8c6995f-a8d3-44e8-a192-81403a78cc29)

I am noticing strange connection to a Server from the Router.
Router is running as AP over eth0.

![grafik](https://github.com/x-wrt/x-wrt/assets/147280037/4cca5930-fadd-4b98-8f93-2922c0ae2555)

The Connection cannot be seen in netstat!
It is blocked by my Firewall because the random Higports are not supported in my Network,
As you can see from my Firewall log. The Source and Destination Ports Change from time to time. 
![grafik](https://github.com/x-wrt/x-wrt/assets/147280037/1f6942f7-977a-4849-af08-f64235496f2f)
The Connection can be seen in tcpdmup on if eth0.
![grafik](https://github.com/x-wrt/x-wrt/assets/147280037/e6615721-e974-4044-9df6-7cb27296da1e)
Running ps w | grep '8.218.31.137' from time to time gives following result
![grafik](https://github.com/x-wrt/x-wrt/assets/147280037/be3c82e8-50a0-4c8d-98cd-62baf13b2afb)
This seems to be Ping to the same IP Adress originating from Busybox.
I cannot track easy because the process disappears. 
Not sure if this is the same Request as in the Firewall Log. No Cron Jobs found triggering this ping.
How to stop it ? 
What is this UDP Connection ?

**Comment by ptpt52** [comment]
it is connection by natcap, is part of remote web luci.
you need to stop and disable all natcapd to stop them.
```
/etc/init.d/natcapd disable
reboot
```

**Comment by TobiKi400** [comment]
Can confirm requests are not there anymore after disdabling natcapd.
Closing Issue. 
Thanks!
