### ISSUE TITLE
小米路由器3，sysupgrade时，报文件格式错误

### ISSUE THREAD

**Issue by henryhwang** [x-wrt/x-wrt#37]
小米路由器3，之前已经成功从官方固件刷到了你的x-wrt。最近想升级固件，下载了你的最新x-wrt，用sysupgrade时，系统报文件格式错误。
请问，必须刷回官方再装新版才能升级吗？有什么办法直接升级吗？

**Comment by ptpt52** [comment]
具体什么版本，如果版本太老了，确实不兼容，可能需要命令强制刷

一般是ssh 登录后，sysupgrade -F  命令强制刷

**Comment by henryhwang** [comment]
一年前的版本，好像当时固件还是netcap开头的名字。-F是强制升级吧，这个情况可以强制刷吗？

**Comment by ptpt52** [comment]
可以，-F 就行。
