### ISSUE TITLE
刷完下载页面下载的固件 直接通电不亮灯了 ，。

### ISSUE THREAD

**Issue by zow2023** [x-wrt/x-wrt#376]
E8450在openwrt 固件的页面升级x-wrt-24.01-b202402242121-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade .itb这个文件 重启后 直接不亮灯了。求大佬指教

**Comment by ptpt52** [comment]
这个你不能强制升级的。提示不兼容就不要升级。

**Comment by ptpt52** [comment]
正确的刷机升级步骤，请看这里
https://github.com/openwrt/openwrt/commit/6aec3c7b5bf5e5a999a12121dfa71963afb6f003#commitcomment-139151946

**Comment by zow2023** [comment]
哎 大意了  大佬能指引一个修砖的出去吗？现在连接串口 直接是这了
![886](https://github.com/x-wrt/x-wrt/assets/125123077/9e3b857f-daa7-4556-a863-922bcaa978ad)

**Comment by zow2023** [comment]
这是不是要编程器了？这机器还很新 想折腾一下的  我只是个喜欢折腾的小白  感谢你的即时回复先。

**Comment by ptpt52** [comment]
没救了也许。

**Comment by ptpt52** [comment]
也许试试 https://www.cnblogs.com/p123/p/18046679
@zow2023
