### ISSUE TITLE
希望支持：小米路由器4A 产品型号：R4AC

### ISSUE THREAD

**Issue by soDLL** [x-wrt/x-wrt#54]
我买了一台：小米路由器4A 产品型号：R4AC
不懂现在有可以刷的固件吗，
没有的话，希望后续支持一下，多谢了。

**Comment by ptpt52** [comment]
最近官方已经支持了，但是没有很好的刷机方法
https://github.com/x-wrt/x-wrt/commit/522d5ff42835f7ad01c090b9ea1863f5d56b91d3

相关论坛讨论：https://forum.openwrt.org/t/xiaomi-mi-router-4a-gigabit-edition-r4ag-r4a-gigabit-fully-supported-but-requires-overwriting-spi-flash-with-programmer/36685
