### ISSUE TITLE
English language

### ISSUE THREAD

**Issue by sistema32** [x-wrt/x-wrt#63]
Can u add english language to the firmware. 
Where i can find a install tutorial for Wavlink WL-WN570HA1?

**Comment by LGA1150** [comment]
```
uci set luci.main.lang=en
uci commit luci
```

**Comment by Jarusz** [comment]
> 
> 
> ```
> uci set luci.main.lang=en
> uci commit luci
> ```

how do i acces ssh on x-wrt?
when im trying to use the default root login, it says "No supported authentication methods available (server sent: publickey)
