### ISSUE TITLE
求教，无线桥接模式的问题

### ISSUE THREAD

**Issue by mkiii** [x-wrt/x-wrt#65]
Wireless Overview 界面，使用5G无线扫描信号，选择主路由的5G wifi，输入wifi密码及新interface的名称，防火墙选择wan，保存。
然后新建的wifi，如果mode选择Client，可以成功连上主路由的wifi，但是子路由就变成主路由下的一个客户机，子路由下的客户机等于套了两层NAT；如果mode选择Access Point，无法成功连上主路由的wifi。
请问，想要达成子路由无线桥接主路由，子路由下客户机从主路由获取内网地址的效果，该如何配置？

**Comment by ptpt52** [comment]
模式 client
网络选择 lan
lan口关闭DHCP
lan口修改IP地址

**Comment by mkiii** [comment]
> 模式 client或者 client wds
> 网络选择 lan
> lan口关闭DHCP
> lan口修改IP地址
主路由网段192.168.1.0/24，子路由lan口设置192.168.2.0/24。
那么现在子路由的lan需要调整成和主路由一样的网段，还是保持不变？
