### ISSUE TITLE
竞斗云2.0原厂u-boot支持128m固件

### ISSUE THREAD

**Issue by shanpo** [x-wrt/x-wrt#77]
目前竞斗云2.0安装openwrt基本上都要求更换bootloader，但实际上原厂u-boot支持64m/128m固件启动。如果保留原厂bootloader，有利于设备获得openwrt官方支持。

**Comment by ptpt52** [comment]
是否保留bootloader，和本固件有什么关系呢，刷机的人自己决定的事情。

**Comment by shanpo** [comment]
跟固件确实没有关系。
