### ISSUE TITLE
Phicomm K2T A1/A2/A3 board (16MB flash)和Phicomm K2T有啥区别？

### ISSUE THREAD

**Issue by molun** [x-wrt/x-wrt#87]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by molun** [comment]
s+s有点难用，可以换成plus或者passwall吗

**Comment by ptpt52** [comment]
没去比，不支持。
