### ISSUE TITLE
内核日志和软件包的luci呢？

### ISSUE THREAD

**Issue by daiaji** [x-wrt/x-wrt#88]
怎么回事？
feed坏了？

**Comment by ptpt52** [comment]
精简了。

**Comment by daiaji** [comment]
> 精简了。

问题是我连装都装不了啊，大哥，至少留个源吧…

**Comment by ptpt52** [comment]
@daiaji 
安装软件的教程，参考 https://blog.x-wrt.com/docs/opkg/

**Comment by daiaji** [comment]
@ptpt52 我知道怎么用opkg，问题是那几个软件包，你不默认安装，至少留下软件源，方便我编译的时候安排上。
