### ISSUE TITLE
HC5861 mt7620 2.4g wifi 冲突，死机

### ISSUE THREAD

**Issue by SuperWangCC** [x-wrt/x-wrt#89]
**Describe the bug**
最新固件，5gwifi正常，而2.4g无法连接（一有客户端连接就会重启）

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ptpt52** [comment]
你好，版本号发出来一下。

**Comment by SuperWangCC** [comment]
b202002230943这个
