### ISSUE TITLE
essedma 延迟较高

### ISSUE THREAD

**Issue by ykzj** [x-wrt/x-wrt#93]
在opboot里，通过电脑连接网线，ping值低于1ms，刷好x-wrt之后，电脑连接网线ping值高于2ms，大概在2-3ms，怀疑是essedma驱动导致的延迟。

**Comment by ptpt52** [comment]
跟 essedma没关系的，可能是cpu的原因。

**Comment by ykzj** [comment]
如果是cpu原因的话，在opboot里的延迟又正常

**Comment by ptpt52** [comment]
嗯嗯，我百思不得其姐

**Comment by ptpt52** [comment]
你试试 
```
echo performance > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
```

**Comment by ykzj** [comment]
已经将governor调整为performance模式，延迟没有改善。

我没有使用缺省的ondemand，选择的schedutil，并且将最低频率设置为200MHz，以及500Mhz，延迟没有变化。

从/proc/interrupts 可以看到，ess_edma的tx队列绑定到了不同的cpu上，rx队列都是绑定到了cpu0

发自我的iPhone

在 2020年3月27日，08:14，Chen Minqiang <notifications@github.com> 写道：

﻿
你试试

echo performance > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor

**Comment by ptpt52** [comment]
我测试过，这样改可以ping 0.9ms

**Comment by ykzj** [comment]
好的，有机会我再试试

发自我的iPhone

在 2020年3月27日，09:02，Chen Minqiang <notifications@github.com> 写道：

﻿
我测试过，这样改可以ping 0.9ms
