### ISSUE TITLE
ess_edma c080000.edma: IPv6 not supported

### ISSUE THREAD

**Issue by daiaji** [x-wrt/x-wrt#94]
https://www.right.com.cn/forum/thread-1529920-1-1.html
从这边描述来看
ipv6用着没问题
但我这边好像会导致断连
主线那边什么时候换掉ess_edma？

**Comment by ptpt52** [comment]
这个打印是 收包RPS调度不支持ipv6而已不影响网络问题。如果断连和这个无关。
什么情况发生断流，我没发现。
